[package]
name = "get_bitcoin_price"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = '0.12.4'
reqwest = "0.10.0"
tokio = { version = "0.2", features = ["full"] }
